### ISSUE TITLE
Broken links in 2015 report

### ISSUE THREAD

**Issue by srid** [ActualFreedom/home#3]
The two links in https://github.com/ActualFreedom/home/wiki/Ballina-Trip-2015 are broken.

**Comment by csaftoiu** [comment]
Fixed it! We should use internal links for wiki references (i.e. `[[link title|Page Name]]`) instead of external links (i.e. `[link title](url)`) since they get marked as red if the page doesn't exist.

**Comment by csaftoiu** [comment]
Also I can't close this issue for some reason ... any reason why?

**Comment by srid** [comment]
@csaftoiu try again, i just made you an owner of this organization.
